### PR TITLE
GUI improvements

### PR DESCRIPTION
**Pull request by haroldGomez**
Hi Mike,

I'm done with the GUI for now. Please take a look at my new changes and please check how the GUI looks under OS X.

Best,

### CODE REVIEW

**Comment by mhucka** [comment]
This looks fine. 

There are two regressions, though.  One that the "Convert" button now uses very small font on OSX. Here's an attempt at including a screenshot to show what I mean:

moccasin-font

The second is that the spacing between the items in the 2nd panel is too small, leading them to be partially on top of each other.  

Is there any way to fix those issues before we merge into 'master'?

**Comment by mhucka** [comment]
Closing this request so that Harold can create a new one with an updated version of the files.

**Comment by mhucka** [comment]
Moving ahead with the merge.

**Comment by haroldGomez** [comment]
Great. I'll delete my branch. Thanks!

On Wed, Apr 1, 2015 at 4:28 PM, Mike Hucka <notifications@github.com> wrote:

> Merged #5 <https://github.com/sbmlteam/moccasin/pull/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbmlteam/moccasin/pull/5#event-271036829>.
>



-- 
Harold Gómez
Bioinformatics PhD. Candidate, Boston University
Graduate School of Arts & Sciences

**Pull request merged**
