### PR TITLE
Syntax highlighting

### PR DESCRIPTION
**Pull request by haroldGomez**
I found a way to enable syntax highlighting with a wxpython widget and pygments. Please let me know what you guys think.

### CODE REVIEW

**Comment by mhucka** [comment]
You did it!  Congratulations. This totally works!

There is a tiny little oddity: an outlined cursor appears to be left on the left bracket of the return value of the Matlab function.  I attach a screenshot that shows this -- it's the red outlined box around the '[' in the first line.

moccasin-highlight-oddity

**Comment by haroldGomez** [comment]
Hi Mike,

On Thu, Apr 9, 2015 at 7:58 PM, Mike Hucka <notifications@github.com> wrote:

> You did it! Congratulations. This totally works!
>
Phew, thanks!

> There is a tiny little oddity: an outlined cursor appears to be left on
> the left bracket of the return value of the Matlab function. I attach a
> screenshot that shows this -- it's the red outlined box around the '[' in
> the first line.
>
Odd, must be an OS-dependent thing as I don't see it on Windows. I will
test on the loaned MAC that I recently got my hands on and make the
appropriate changes.

> [image: moccasin-highlight-oddity]
> <https://cloud.githubusercontent.com/assets/1450019/7079451/66f5268e-def2-11e4-82be-051c9d50c8dd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbmlteam/moccasin/pull/10#issuecomment-91383967>.
>

Best,


-- 
Harold Gómez
Bioinformatics PhD. Candidate, Boston University
Graduate School of Arts & Sciences

**Comment by haroldGomez** [comment]
Alright, I think this fixes the issue you pointed out and at the same time
modifies the colors being used to be more eye-pleasing (no more fluorescent
green!).

Let me know what you think.

On Fri, Apr 10, 2015 at 10:53 AM, Harold Gomez <rolo.1987@gmail.com> wrote:

> Hi Mike,
>
> On Thu, Apr 9, 2015 at 7:58 PM, Mike Hucka <notifications@github.com>
> wrote:
>
>> You did it! Congratulations. This totally works!
>>
> Phew, thanks!
>
>> There is a tiny little oddity: an outlined cursor appears to be left on
>> the left bracket of the return value of the Matlab function. I attach a
>> screenshot that shows this -- it's the red outlined box around the '[' in
>> the first line.
>>
> Odd, must be an OS-dependent thing as I don't see it on Windows. I will
> test on the loaned MAC that I recently got my hands on and make the
> appropriate changes.
>
>> [image: moccasin-highlight-oddity]
>> <https://cloud.githubusercontent.com/assets/1450019/7079451/66f5268e-def2-11e4-82be-051c9d50c8dd.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sbmlteam/moccasin/pull/10#issuecomment-91383967>.
>>
>
> Best,
>
>
> --
> Harold Gómez
> Bioinformatics PhD. Candidate, Boston University
> Graduate School of Arts & Sciences
>



-- 
Harold Gómez
Bioinformatics PhD. Candidate, Boston University
Graduate School of Arts & Sciences

**Comment by mhucka** [comment]
This works great!  Awesome work!

I'll go ahead and merge it to master.

**Pull request merged**
